### GET list ------------------------------------------------------------

### GET all users
GET http://localhost:3000/users HTTP/1.1



### GET all posts
GET http://localhost:3000/posts HTTP/1.1



### GET item ------------------------------------------------------------

### GET a single item
GET http://localhost:3000/users/1 HTTP/1.1



### POST ------------------------------------------------------------

### POST user 
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "name" : "Verity",
  "email" : "verity@joara.com"

}

### POST post
POST http://localhost:3000/6/posts/ HTTP/1.1
content-type: application/json

{
  "title": "How to be a vegan",
  "content": "Hello world!"
}



### PATCH ------------------------------------------------------------

### PATCH member
PATCH http://localhost:3000/users/2 HTTP/1.1
content-type: application/json

{
  "name" : "joel"
}

### PATCH post
PATCH http://localhost:3000/posts/6 HTTP/1.1
content-type: application/json

{
  "content" : "Don't eat meat!"
}


### DELETE ------------------------------------------------------------

### DELETE item
DELETE http://localhost:3000/users/2 HTTP/1.1

### DELETE posts
DELETE http://localhost:3000/posts/9 HTTP/1.1
